#!/bin/bash

set -e

ME=$(basename $0)
DOTFILES_ROOT="$(dirname $(readlink -f ${ME}))"

info() {
    printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
    printf "\r  [ \033[0;33m?\033[0m ] $1 "
}


success() {
    printf "\r\033[2K [\033[00;32mOK\033[0m] $1\n"
}

fail() {
    printf "\r\033[2K [\033[00;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}

link_files() {
    ln -sf $1 $2
    success "linked $1 to $2"
}

install_dotfiles() {
    reinstall=false
    if [ $1 == 'reinstall' ]; then
        reinstall=true
    fi
    for source in $(find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink); do
        dest="$HOME/.$(basename ${source%.*})"
        if [ -d $source ]; then
            if ${reinstall}; then
                rm -rf $dest
            else
                mv $dest $dest.bak
            fi
            source=$source/
        fi
        link_files $source $dest
    done
}

main() {
    setup_gitconfig
    install_dotfiles $1
}

main $@
